RubyLabb/config/routes.rb
RubyLabb::Application.routes.draw do
  get "sessions/login"

  resources :projects do 
    resources :tickets
    end 
  resources :users

  root :to => 'projects#index'
  match "login", to: "sessions#login"
  match "logout", to: "sessions#logout"
  match "/projects/:id/tickets" => "tickets#show"
  match "/projects/:id/tickets/create" => "tickets#new"
  match "/projects/:id/tickets/:ticket_id/edit" => "tickets#edit"
  match "/home" => "home#index"

  match ':controller(/:action(/:id))(.:format)'
end

RubyLabb/app/models/project.rb
class Project < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :tickets, :dependent => :delete_all
  
  attr_accessible :name, :description, :start_date, :end_date
  
  validates :name,
            :presence => { :message => "Add a name for the project please"},
            :length => { :minimum => 3, :message => "The name must be at least 3 charachters"}
            
  validates :description,
  :presence => { :message => "Add a description for the project please"},
  :length => { :minimum => 50, :message => "The description must be at least 50 charachters" }

  
end

RubyLabb/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  #Kontrollerar inloggningen
  before_filter :check_login
  def index
      user_id = session[:user_id]
      @projects = Project.all
      @user = User.find(user_id)
      @tickets = Ticket.all(:conditions => { :status_id => [2] })
  end
  
  def show
    projectId = params[:id].to_i 
    @project = Project.find(projectId)
    @ticket = Ticket.new
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(params[:project])
    @project.user_id = session[:user_id]
    if @project.save
      flash[:notice] = "Successfully created " + @project.name
      user = User.find(session[:user_id])
      user.projects << @project
      redirect_to projects_path
    else
      flash[:error] = "Could not create project, try again."
      render :action => 'new'
    end
  end
  
  def destroy
    #Kolla så att inloggad användare stämmer överrens med ägaren.
    @project = Project.find(params[:id]) 
    if @project.user_id == session[:user_id]
       @project.destroy()
      flash[:notice] = "Your project has been removed"
      redirect_to projects_path
    else
      flash[:error] = "The project couldn't be removed, are you sure you are the owner?"
      render :action => 'index'
    end

  end
  
  def edit
    @project = Project.find(params[:id])
    if @project.user_id == session[:user_id]

    else
      flash[:error] = "The project couldn't be edited, are you sure you are the owner?"
      render :action => 'projects', :action => "show", :id => @project.id
    end
  end
  
  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project saved."
      redirect_to :controller=> "projects", :action => "show", :id => @project.id
    else
      render :action => "edit"
    end
    
  end
  
  def join
    project = Project.find(params[:id])
    user = User.find(session[:user_id])
    user.projects << project
     
    flash[:notice] = "You have successfully joined the project"
    redirect_to :controller=> "projects", :action => "show", :id => project.id
  end
  
  def leave
    
  end

end

RubyLabb/app/helpers/projects_helper.rb
module ProjectsHelper
end

RubyLabb/app/views/projects/edit.html.erb
<% content_for :menu do %>
  <li><a href="/home">Home</a></li>
  <li><a href="/projects">All projects</a></li>
  <li class="active"><a href="/projects/new">New project</a></li>
  <li><a href="/users">Users</a></li>
<% end %>
<div class="row">
    <div class="span10 gradientGray">
      <h2>Edit project</h2>

      <%= render :partial => "shared/projectForm" %>

  </div>
</div>

RubyLabb/app/views/projects/index.html.erb
<%= render :partial => "shared/message" %>

<% content_for :menu do %>
  <li><a href="/home">Home</a></li>
  <li class="active"><a href="/projects">All projects</a></li>
  <li><a href="/projects/new">New project</a></li>
  <li><a href="/users">Users</a></li>
<% end %>

<div class="row">  
  <div id="mainDiv" class="span12 gradientGray">
    <h1>All projects</h1>
      <% if @projects.count > 0 %>
        <% @projects.each_with_index do |project, index| %>
          <% if index%3 == 0 %>
            <div class="row">
          <% end %>
              <div class="span4 projectDiv">
                <h3><%= link_to project.name, project_path(project)%></h3>
                <p class="creator"><%= link_to User.find(project.user_id).first_name, user_path(User.find(project.user_id))%></p>
                <p class="description"> 
                  <% first_30_words = project.description.split(" ").first(30).join(" ") %>
                  <%= first_30_words%>
                  <%= link_to "[...]", project_path(project)%>
                </p>
              </div>
          <% if index%3 == 2%>
            </div>
          <% end %>      
  
          <% end %>
        <% else %>
        <p>No projects found...lazy co-workers? </p>
      <% end %>
  </div>
  <% if @tickets.count > 0%>
    <hr>
    <div class="span12">
      <h3>Showing all critical tickets</h3>
      <ul class="inline">
        <% @tickets.each do |ticket|%>
          <% cssClass = ticket.status.status_name.gsub(/ /, '-').downcase %>
          <li><%= link_to ticket.name, ticket_path(ticket), :class => cssClass%></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

RubyLabb/app/views/projects/new.html.erb
<% content_for :menu do %>
  <li><a href="/home">Home</a></li>
  <li><a href="/projects">All projects</a></li>
  <li class="active"><a href="/projects/new">New project</a></li>
  <li><a href="/users">Users</a></li>
<% end %>
<div class="row">
    <div class="span12 gradientGray">
      <h2>Add a new project</h2>
      
      <%= render :partial => "shared/projectForm" %>
      
  </div>
</div>

RubyLabb/app/views/projects/show.html.erb
<% content_for :menu do %>
  <li><a href="/home">Home</a></li>
  <li class="active"><a href="/projects">All projects</a></li>
  <li><a href="/projects/new">New project</a></li>
  <li><a href="/users">Users</a></li>
<% end %>

<%= render :partial => "shared/message" %>

<div class="row">
    <div class="span12 gradientGray">
        <h2><%= @project.name %></h2>
        <p>Project owner: <%= link_to user = (User.find(@project.user_id).first_name), user_path(User.find(@project.user_id)) %></p>
        <p><strong><%= @project.start_date.strftime("%Y-%m-%d") %></strong> to <strong><%= @project.end_date.strftime("%Y-%m-%d") %></strong></p>
        <p id="singleProjectDescription"><%= @project.description %></p>
    <hr>
      <div class="row">
        <div class="span12">
          <h2><strong>Details</strong></h2>
          <div id="projectFirst" class="span5 projectInfoDiv">
            <h4>Members</h4>
            <ul class="inline">
              <% @project.users.each do |user| %>
                <% fullName = user.first_name + " " + user.last_name %>
                <li><%= link_to fullName, user_path(user) %></li>
              <% end %>
            </ul>
          </div>
          <div id="projectSecond" class="span5 projectInfoDiv offset1">
            <h4>Tickets <span class="allTickets"><%= link_to "Show all tickets", :controller => "tickets", :action => "index", :id => @project.id %></span></h4>
            <ul class="inline">
              <% @project.tickets.each do |ticket| %>
              <% cssClass = ticket.status.status_name.gsub(/ /, '-').downcase %>
                <li><%= link_to ticket.name, {:controller => "tickets", :action => "show", :id => ticket.id} , :class => cssClass %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <hr>
    <div class="row">
      <div class="span12">
        <ul class="inline">
          <li><%= link_to "Back", {:controller => "projects", :action => "index"}, :class => "btn btn-info" %></li>
          <% members = @project.users%>
          <% if @project.user_id == session[:user_id] %>
            <li><%= button_to "Delete", {:controller => "projects", :action => 'destroy', :id => @project.id}, :method => :delete, :class => "btn btn-danger" %></li>
            <li><%= button_to "Edit", {:controller => "projects", :action => 'edit', :id => @project.id}, :method => :get, :class => "btn btn-warning" %></li>
          <% end %>
          <% if members.include?(User.find(session[:user_id])) %>
            <li><%= link_to "New ticket", "/projects/" + @project.id.to_s + "/tickets/create", :class => "btn btn-success" %></li>
          <% else %>
            <li><%= button_to "Join", {:controller => "projects", :action => 'join', :id => @project.id}, :method => :put, :class => "btn btn-success" %></li>
          <% end%>
        </ul>
      </div>
    </div>
  </div>
</div>